moxin-frontend/resources/icons/jump_to_bottom.svg
moxin-frontend/src/chat/chat_panel.rs

This is a quick addition of the feature, but with some limitations because we don't have yet a reliable way to track if the scroll is at the end in the PortalList (I need to do more research).
Also, styling will need to be reworked because the Figma design has a shadow effect hard to archive in Makepad.

Add jump to bottom button in chat

---

moxin-frontend/src/landing/model_files_list.rs
moxin-frontend/src/my_models/downloaded_files_table.rs
moxin-frontend/src/my_models/my_models_screen.rs
moxin-frontend/src/shared/mod.rs
moxin-frontend/src/shared/utils.rs

I noticed that currently most models are providing their file size, however it is now in provided in bytes instead of formatted to GB like before, i.e. `1.09 GB` is now `1095216660`
This PR updates the Modes Files List in the landing page, and My Models screen (header and table) with proper formatting.
Files list in landing screen:
My Models:
(In the header, if the total diskspace is < 1GB it will format to MB, i.g. `1 Model, 459 MB Diskpace`)

Add proper formatting of model sizes

---

moxin-frontend/src/app.rs
moxin-frontend/src/chat/chat_line.rs
moxin-frontend/src/landing/model_card.rs
moxin-frontend/src/my_models/delete_model_modal.rs
moxin-frontend/src/my_models/downloaded_files_table.rs
moxin-frontend/src/my_models/mod.rs
moxin-frontend/src/my_models/model_info_modal.rs
moxin-frontend/src/shared/resource_imports.rs
moxin-frontend/src/shared/utils.rs

Adds the info modal to My Models view
Does not yet implement the copy to clipboard action, since that requires some support from Makepad.
https://github.com/project-robius/moxin/assets/22042418/9321e897-e300-4a72-b282-5f8efdb86e4a

My Models - Add model info modal

---

moxin-frontend/resources/icons/go_to.svg
moxin-frontend/src/app.rs
moxin-frontend/src/chat/chat_panel.rs
moxin-frontend/src/chat/model_selector.rs
moxin-frontend/src/data/store.rs
moxin-frontend/src/my_models/downloaded_files_table.rs

Adds a button to the My Models table, with a 'Resume Chat' action if there's a current active chat.
https://github.com/project-robius/moxin/assets/22042418/57989fa1-9db0-47fc-9071-83beff2a0167

Implement resuming chat in my models table

---

moxin-frontend/src/chat/chat_line.rs
moxin-frontend/src/chat/chat_panel.rs
moxin-frontend/src/data/chat.rs
moxin-frontend/src/data/store.rs

There is now an option to regenerate the conversation upon editing a user prompt.
TBD: Final design of the option will be checked by design team.

Regenerate chat option

---

moxin-backend/src/backend_impls.rs
moxin-frontend/src/chat/chat_panel.rs
moxin-frontend/src/chat/model_selector.rs
moxin-frontend/src/data/chat.rs
moxin-frontend/src/data/store.rs
moxin-frontend/src/my_models/delete_model_modal.rs
moxin-frontend/src/my_models/downloaded_files_table.rs
moxin-protocol/src/protocol.rs

Implements the file deletion in the My Models table. 
Automatically refreshes state int he landing screen files.
If the model is actively loaded it will be ejected, and the chat panel will be reset.
https://github.com/project-robius/moxin/assets/22042418/53720c82-e8c7-4532-b0c4-e22011af8c17

Implement delete model file

---

moxin-frontend/src/landing/downloads.rs
moxin-frontend/src/shared/icon.rs

Adds rotation to the download mangers' collapse icon to match the collapsed state.
Also adds a rotation_angle flag to the `Icon` widget.
https://github.com/project-robius/moxin/assets/22042418/207b2ac5-2ef2-4aaa-9f27-4bb11fcea024

Add rotation to downloads collapse icon

---

moxin-frontend/src/app.rs
moxin-frontend/src/chat/chat_panel.rs
moxin-frontend/src/chat/model_selector.rs

update to latest designs.
when there are downloaded models and none of them are selected:
- always show message input
when there are no downloaded models:
- update texts
-  always show message input
- show button "go to discover"
- update text color

Redesign chat screen when there are no downloaded models

---

moxin-frontend/src/data/search.rs
moxin-frontend/src/data/store.rs
moxin-frontend/src/landing/landing_screen.rs
moxin-frontend/src/landing/model_list.rs

This PR fixes issues with internet disconnection or unavailable server errors, which was breaking the Explore section once it happened.
Now, the user is informed when there is a connectivity issue. Also, the application keeps responsive to try again the search.

Recover search backend errors

---

Cargo.lock
moxin-frontend/src/app.rs
moxin-frontend/src/chat/chat_panel.rs
moxin-frontend/src/chat/mod.rs
moxin-frontend/src/chat/model_selector.rs
moxin-frontend/src/data/store.rs
moxin-frontend/src/landing/mod.rs
moxin-frontend/src/landing/model_files_item.rs
moxin-frontend/src/landing/model_files_list.rs
moxin-frontend/src/landing/model_list.rs
moxin-frontend/src/my_models/downloaded_files_table.rs
moxin-frontend/src/my_models/mod.rs
moxin-frontend/src/shared/actions.rs
moxin-frontend/src/shared/mod.rs
moxin-frontend/src/shared/widgets.rs
moxin-frontend/src/shared/widgets/c_button.rs

- Replaces the "Downloaded..." button in the landing page with "Chat with Model" and "Resume".
- These work the same as in the "My Models" screen.
- Tried to extract a common reusable button called `CButton` (to avoid name conflicts).
- Seems like a small issue with the cursor got fixed in the landing screen by using that button.
https://github.com/project-robius/moxin/assets/7684329/af64ed9d-1f7e-4e41-9c3b-1732e036581e
https://github.com/project-robius/moxin/assets/7684329/fe195bac-465a-4275-96ab-145cf2b0ae63
https://github.com/project-robius/moxin/assets/7684329/ae417abe-3f57-406a-9f0c-eb0a1bc80b56

Resume and Start chat buttons from landing page

---

Cargo.lock
moxin-frontend/src/app.rs
moxin-frontend/src/landing/download_item.rs
moxin-frontend/src/landing/model_files_item.rs
moxin-frontend/src/landing/model_files_list.rs
moxin-frontend/src/shared/widgets.rs

This PR replaces some of the buttons in the Explore and Download Manager sections to make use of the original widget from Makepad.
It defines a custom `MoxinButton` which is basically a `Button` widget with most of the shader code reimplemented to fit our application design. It follows what we did for the `TextInput` widget (where we have a `MoxinTextInput`).
Now, it has a better look&feel because hovering those buttons has animations in the colors. At the code level, it relying in most idiomatic Makepad code since it is using the `Button` API directly.

Refactor to make use of the original Makepad Button widget

---

moxin-frontend/src/app.rs
moxin-frontend/src/data/store.rs
moxin-frontend/src/landing/download_item.rs
moxin-frontend/src/landing/model_files_item.rs
moxin-frontend/src/landing/model_files_list.rs
moxin-frontend/src/shared/actions.rs
moxin-frontend/src/shared/download_notification_popup.rs

- See download progress of each model file with a progress bar and text.
- Resume, pause, cancel and retry controls inline with the progress.
- [Figma](https://www.figma.com/design/LIaqW5HF3CGtq4XMpDxDMD/MoxinUI---LLM-Desktop-App?node-id=1332-17276&t=QvBkQt8twguLLYZh-0)
- Although not in the design, the decimal precision has been added to the text progress because:
- It's consistent with what we already have.
- Without it, it's difficult to tell quickly if everything is working properly.
- Because of the previous point, the buttons may be placed a bit more on the right than in the design.

Progress and download controls for each model download item in the landing

---

moxin-frontend/src/my_models/downloaded_files_row.rs
moxin-frontend/src/my_models/downloaded_files_table.rs

There were a need to differentiate the first row in this listing in previous versions of the design, but it doesn't seem to be needed in the latest version.
Before:
After:

Fix minor issue with separators in My Models listing

---

Cargo.toml
moxin-backend/src/backend_impls.rs
moxin-backend/src/lib.rs
src/data/filesystem.rs

~~**Note: do not merge this yet, it's messy.**~~ ready now
The problem is that when an app bundle is run, the current working directory is `/` (root), which is read-only on macOS. Thus, the attempt to access `./data.sqlite` is actually an attempt to create the file `/data.sqlite`, which immediately fails because a file cannot be created on the read-only root partition.
Instead of using the current working directory, this commit now changes file paths to be relative to `$HOME`, which will only really work properly on Unix-like environments where the `$HOME` environment variable is defined. Even on Unix-like systems, this isn't *guaranteed* to work, since various sandboxing or environment masking techniques may be in effect.
To actually create the bundle:
1. install cargo-bundle: `cargo …

Make Moxin runnable from a macOS `.app` bundle.

---

Cargo.lock
Cargo.toml
moxin-backend/Cargo.toml
moxin-backend/src/lib.rs
moxin-runner/Cargo.toml
moxin-runner/src/main.rs

This most commonly occurs in an environment where the app was installed by a packaged installer.
* The moxin crate now generates a binary called `_moxin_app`, which intentionally does not begin with moxin, such that a shell autocomplete does not suggest both "moxin" and "moxin-runner", which is confusing and misleading, because directly running "moxin" previously would not work.
* The moxin-runner crate now generates a binary called `moxin`, which ensures that if a user runs the `moxin` command, everything still works as intended.
* These changes still allow `cargo run` to work as normal, in addition to
`cargo run -p moxin-runner`.
* Removed unnecessary dependencies; addressed a few minor warnings.

Rename binaries to avoid accidental invocation of the moxin app

---

src/chat/chat_panel.rs

- Centralized everything mutating visibility states of chat panel into a single method so it's easier to debug and to define what is shown in each possible state.
- Fixed multiple visibility overlap bugs.
- Model selector initially empty and visible.
- As agreed , state is kept in the widget as it was before giving the chance to change it from there, but is computed from store when an event happens (the mouse is moved, or whatever).
- Improved autoscroll behavior a bit. Autoscroll should now be reliable if you never scrolled up or if you did but pressed the jump to bottom button. Other issues are harder to fix without modifying the portal list widget.

fix - chat panel visibility states + refactor - local state reconciliation

---

README.md

Codesigning/notarization now works as expected, so these warnings will not show up.

Remove outdated parts of README about running macOS app bundles

---

Cargo.lock
Cargo.toml
src/main.rs

Tested working on Debian-like Linux and macOS.
Note that this functionality will only work for properly packaged application bundles (i.e., using cargo-packager) that have been installed on your system, e.g., using `sudo dpkg -i` on Linux or installing the app bundle via the `moxin-*.dmg` disk image on macOS.
On Linux, the handled URLs are appended to the file `/tmp/moxin_incoming_url.txt`.
On macOS, that file is located at `$TMPDIR/moxin_incoming_url.txt`.

Use `robius-url-handler` to handle incoming URLs with scheme `moxin://`

---

packaging/moxin.desktop

Defining the `StartupWMClass` should allow windows to be properly grouped, once we add support for that into Makepad's X window handling.

Linux: update .desktop file to support handling multiple URLs and define WMClass

---

src/landing/model_files.rs

When user switched to see all files for a model, if later the listing was changed to display different models the toggle button was not reseted to the initial position. This PR makes sure the default option is always "Show Only Recommended"

Make sure Show Only Recommended files is the default selected option

---

Cargo.toml
README.md

These are now specified for Debian and Pacman packages.
Uses a new version of cargo-packager, as now specified in the README.
Also fixes AppImage packages to _always_ work even on a fresh Linux install.

Auto-determine dependencies for Linux packaging

---

src/data/chats/chat.rs

This adds support for chat interactions without streaming responses. #133 is adding a settings form with a toggle option to turn on/off the streaming, so it will be testable when it gets merged.

Support chat responses when stream option is off

---

src/app.rs
src/chat/chat_history_card.rs
src/chat/delete_chat_modal.rs
src/chat/mod.rs

- Adds a confirmation modal when trying to delete a chat.
- The modal is almost a copy of the existing modal for deleting models.
- [Design](https://www.figma.com/design/LIaqW5HF3CGtq4XMpDxDMD/MoxinUI---LLM-Desktop-App?node-id=816-4068&t=enlxvJ4uaQS0AlOe-4)
https://github.com/moxin-org/moxin/assets/7684329/deee9d34-07cc-4472-829e-496a51cf1c53

Delete Chat Modal

---

src/chat/chat_line.rs

I was debugging the Chat screen and confirmed we had a `self.redraw(cx)` in a function that was called (indirectly) from a `draw_widget` function body. This change should not affect anything, but let's confirm with more testing.

Avoid redraw call in render logic in Chat

---

src/app.rs
src/chat/chat_history_card.rs
src/chat/chat_line.rs
src/chat/chat_panel.rs
src/chat/model_selector.rs
src/data/chats/chat.rs
src/data/chats/mod.rs
src/data/store.rs
src/landing/model_files_item.rs
src/my_models/downloaded_files_row.rs
src/shared/actions.rs
src/shared/portal.rs

When the user switches to another chat conversation, the last used model is automatically loaded.
In addition, there are two bug fixes:
* Save & Regenerate buttons were visible for AI messages, which was wrong (issue introduced when changed to use Makepad buttons).
* Fixed weird issue when chat messages were not appearing at all (the problems was the scroll position of the messages PortalList when coming from a longest conversation).
Note about existing users: Chat conversations persisted with earlier versions of the app won't auto-select the last used model because this piece of data was never stored. We could use the model used in the first interaction but it doesn't seem to worth adding more code to cover such case. As far the conversation are updated, they will be persisted in our new …

Switch loaded model upon chat change

---

src/chat/chat_panel.rs

When you try to scroll further than the maximum possible amount, the jump to bottom button flickers.
https://github.com/moxin-org/moxin/assets/7684329/01148994-fe77-4947-b8bf-e0b84f7edc9f
Detect if the end of the list has been reached in a different way. By telling the portal list to render one more item, and when the portal list renders that, flag that the portal list reached the end.

Fix jump to bottom flicker

---

src/data/chats/chat.rs
src/data/chats/mod.rs
src/data/store.rs

- Keep track of the last time a chat has been selected.
- Load the last selected chat on app start.
- Bonus: When deleting the chat, move to the previous one you had selected.
- This change lets me remove the last created chat id function that I think was only being relevant for this arbitrary behavior.
https://github.com/moxin-org/moxin/assets/7684329/efc61e45-d8f1-4b1b-a69a-6a598d459482

Last selected chat memory

---

moxin-backend/src/backend_impls/api_server.rs

fix https://github.com/moxin-org/moxin/issues/158
Because wasi-logging has some bug, let’s just remove it; it’s not actually serving any purpose now.

[BackEnd] remove wasi_logging plugin

---

src/chat/chat_panel.rs

closes https://github.com/orgs/moxin-org/projects/1/views/1?pane=issue&itemId=71621663
https://github.com/user-attachments/assets/39210453-96c8-42d6-8157-29f2748b45dc

place jump to bottom button on the right

---

moxin-backend/src/backend_impls/api_server.rs

Unable to access `http://0.0.0.0:8080/echo` on Windows, but it works on Linux. This causes it to not works on Windows.

[Backend] fix windows

---

moxin-backend/src/backend_impls/api_server.rs

Sometimes we need to set the http_proxy, but incorrect settings can affect access to api-server.wasm. So I’ve configured it so that no proxy is required when accessing api-server.wasm.

[backend] remove proxy when request api-server

---

.github/workflows/ci-build.yml

powershell's `Invoke-WebRequest` is like... comically, laughably bad, and this makes it much much faster to download files.
Building in debug mode plus the above reduces CI time by about 30%.

Make CI builds faster: debug builds, better powershell downloads

---

src/chat/chat_line.rs
src/chat/chat_panel.rs

Assistant message alignment

---

.gitignore
README.md
moxin-backend/src/backend_impls/api_server.rs

With these instructions, Moxin builds and runs but does not yet properly work when loading a model to chat with.
There is still a problem with WasmEdge or Moxin on Windows.

README: add instructions for building and running on Windows x64

---

src/app.rs
src/shared/desktop_buttons.rs
src/shared/mod.rs

Currently the title bar of the application window is invisible (unless hovering on the icons) in Windows.
This is because the default colors for the desktop buttons in Makepad's dark theme defaults to white strokes.
This PR copies over the `DesktopButton` shader and overrides colors and makes some sizing adjustments.

Override desktop buttons styling

---

.github/workflows/ci-build.yml
Cargo.toml
README.md
packaging/before-packaging-command/Cargo.toml

Update README instructions to be more clear about the procedures for installing WasmEdge on different host OSes

Set MSRV to 1.79, as required by `cargo-packager`.

---

src/data/chats/mod.rs

This fix issues related with switching conversations when a chat response is still being streamed. The main issue was that the following model to be loaded got stuck loading. It was quite easy to reproduce if using the "Start Chat" buttons from My Models listing.

Stop chat streaming when switching conversation

---

Cargo.lock
moxin-runner/src/main.rs

Relying on the system-wide installation has myriad problems; this avoids those many problems entirely by only checking the app's data directory for a WasmEdge installation and installing WasmEdge there if it is missing, which guarantees that the specific version and build characteristics of the WasmEdge installation is always under the sole control of Moxin.
As a side note, I'm not sure why there are so many tiny version changes to the `Cargo.lock` file. It seems like every time i build the Moxin workspace on a different host OS, there are tons of minor version changes. Shouldn't hurt anything, but it seems odd.

Use (or install) WasmEdge in the app-specific data directory *ONLY*

---

src/landing/model_card.rs

Fixes #204 
There was an issue where the title or description of some models in the main listing were not visible. The root problem was we were using similar identifiers for the title and description labels in `ModelCard` and `ModelCardViewAllModal` widgets (which is a nested view under the model card view).
The solution is to remove the ambiguity by providing unique identifiers for the labels into the modal widget, so the widget lookup for the labels is what we expect in each case.

Fix intermittent issue with model card title and description labels

---

moxin-runner/src/main.rs

Depends on #200
Ready to merge once #200 is merged.

moxin-runner: explicitly detect CUDA on Linux

---

moxin-runner/src/main.rs

The `install_v2.sh` script does not properly detect CUDA installations at the moment (see #255), so we do the detection ourselves in `moxin-runner` and then pass in the correctly-detected CUDA version as an argument into that bash script.
Partially addresses #225.
Also, this PR allows `moxin-runner` to behave as a general cargo command runner:
```sh
cargo run -p moxin-runner -- cargo build --release
```
which saves Moxin devs a lot of time & effort because they don't have to manually install WasmEdge and set up all the necessary environment variables. Let `moxin-runner` do it for you!
Also closes #207.

Manually detect and force CUDA version passed into `install_v2.sh`

---

README.md

Setting up WasmEdge on Windows is quite difficult to do correctly, so we now default to using `moxin-runner` instead.
Also mentions that we have pre-built releases of Moxin and how Moxin is in beta.

Simplify README with `moxin-runner`-based instructions

---

src/chat/chat_history.rs
src/chat/chat_history_card.rs
src/chat/chat_panel.rs

A problem was introduced in #236 where it is impossible to write in several text inputs in the Chat section interface.
This was happening because the `key_focus` was always set to the main prompt input.
Here we reimplemented the desired behavior (autofocus the prompt input when a new chat is created or we switch between chats) without messing with other text inputs (such as System Prompt, Stop, inline edition of chat messages, etc)

Fix Chat section text inputs focus issues

---

src/app.rs
src/shared/popup_notification.rs

There were two issues with popup notifications displayed when models are downloaded:
* The popup was refusing to be dismissed (e.g. close button not working)
* The user could interact with the dropdown that sits under this floating element (in Explorer section), when it was not the expected thing to happen.
Both issues are addressed in this PR.

Fix problem with click events in popup notifications

---

src/chat/chat_history_card.rs

Fixes #185
This cancels the chat edition whenever a history card's `chat_id` is updated, so that deleting a chat from the history does not cause the editing state to be "moved" into another chat's card.
Whenever a chat is removed, the `ChatHistoryCard` widget that was created for that chat, is re-used for the next one on the list. It's state must be updated accordingly. This changes just reset the state back to default.

Reset edition state when chat history card is re-used

---

Cargo.lock
Cargo.toml
src/app.rs
src/chat/chat_history_card.rs
src/chat/chat_line.rs
src/chat/chat_panel.rs
src/chat/chat_params.rs
src/data/store.rs
src/landing/model_files_list.rs
src/landing/search_bar.rs
src/landing/sorting.rs
src/my_models/my_models_screen.rs
src/shared/actions.rs
src/shared/modal.rs
src/shared/popup_notification.rs
src/shared/tooltip.rs
src/shared/widgets.rs

This PR changes Makepad version to the latest in `rik` branch.

Catch up makepad

---

src/data/chats/mod.rs

I solved the issue by removing the model-generated reply from the corresponding array when the user clicks the cancel button. However, this creates a situation where the user's questions may appear next to each other. I'm not sure if this is the best solution.

fix-issue-206

---

moxin-backend/src/backend_impls/api_server.rs
moxin-backend/src/backend_impls/mod.rs

* Fixed chat model name as "moxin-chat"
* Fixed embedding model name as "moxin-embedding"
The frontend doesn't need to change because I've already replaced the model name in the request on the backend

[Backend] fix model name

---

Cargo.lock
src/chat/chat_line.rs
src/chat/chat_panel.rs

This PR bumps the Makepad version. Some adjustments were needed to avoid a visual problem that was very noticeable in markdown-formatted messages.
This screenshot demonstrates the font color issue (bumping to most recent Makepad version, without the other changes in this PR)

Fix visibility of markdown-formatted message

---

src/chat/model_selector.rs
src/chat/model_selector_list.rs

To avoid branch conflicts, I didn't modify the code
```rust
for action in actions
.iter()
.filter_map(|action| action.as_widget_action())
```
in the `chat_panel` for this commit because I already made those changes in pr #293 .

refactor ModelSelectorAction

---

src/app.rs
src/chat/chat_history.rs
src/chat/chat_panel.rs
src/data/chats/chat.rs
src/data/chats/mod.rs
src/data/chats/model_loader.rs
src/data/downloads/download.rs
src/data/downloads/mod.rs
src/data/search/mod.rs
src/data/store.rs
src/landing/download_item.rs
src/landing/landing_screen.rs
src/landing/model_files_item.rs
src/landing/model_list.rs
src/settings/settings_screen.rs

- Replaced `Event::Signal` pattern matchings with reactions to specific cross-thread actions.
- Replaced `SignalToUI::set_ui_signal()` with `Cx::post_action(...)`.
- Replaced "polling" in the store when a signal comes, with normal action handling and routing.

Signals to explicit actions

---

src/chat/chat_line.rs
src/chat/chat_panel.rs

There is a problem: Sometimes Makepad cannot immediately render this dot.

Add a dot at the end of chat lines during model replies to make the responses look smoother.

---

src/data/chats/mod.rs

Currently, if you create many new chats with the "New Chat" button, and then you change the currently loaded model, the selected model for all the chats will change.
If there is a loaded model, associate it to the new chat.

Remember model used at creation time of a model

---

src/chat/chat_history.rs
src/chat/chat_history_card.rs
src/chat/chat_panel.rs

I noticed that when switching from a long chat to a new agent chat, portal list bugs due to scroll reset not being triggered. Some dev commits ago this caused the app to crash but now it just causes a visual and performance issue.
Actually, this issue can be provoked by mixing other kinds of user interaction:
- If you are in a long chat, then you go to "My Models" and then you start a new chat with the same model from there.
- If you have 2 chats, one long and one short, and being at the long one you delete it.
And there may be more I'm not noticing now. Or at least, there will be more. 
- Do not try to react to every possible action that my update current chat id.
- Instead, directly react to the chat id change itself :)
There are two ways to do this without a reactivity abstraction:
- …

Fix chat switching

---

moly-backend/src/backend_impls/api_server.rs

* Update wasm to support `moxin-chat-7b`
* Load wasi_logger. Since `wasmedge 0.14.1`, `wasi_logger` has been a built-in plugin for `wasmedge`.

Update backend wasm to support `moxin-chat-7b`

---

src/chat/chat_history_card.rs
src/data/chats/mod.rs
src/data/store.rs

When switching to a different chat from one that was streaming, it will not always cancel the previous streaming causing issues in the UI.
Some examples of cancellation not happening are when creating a new chat or when deleting the streaming chat.

Fix chat switch streaming cancel

---

src/chat/chat_history_card.rs
src/chat/chat_panel.rs
src/shared/actions.rs

- Remove a `self.redraw(cx)` that was indirectly being used inside `ChatHistoryCard`'s `draw_walk` causing a loop.
- Explicitly redraw `ChatHistoryCard` on title update, whose reaction was depending on the loop bug.
- Remove a `self.redraw(cx)` that was indirectly being used inside `ChatPanel`'s `draw_walk`, but only when the stop button styles are updated (after sending a message).
I played with the app while keeping an eye on the process CPU and GPU usage. Also added the following to `ChatPanel`'s `draw_walk` to control that flow is not in a loop.
```rust
eprintln!(
"ChatPanel::draw_walk ({})",
std::time::SystemTime::now()
.duration_since(std::time::UNIX_EPOCH)
.unwrap()
.as_millis()
);
```
Closes #329

Fix redraw loop

---

packaging/before-packaging-command/src/main.rs

This [pr](https://github.com/moxin-org/moly/pull/330)  requires the wasi-logger plugin which is built into wasmedge 0.14.1.
And wasi-logger in wasmedge 0.14.0 has bug.
So we need update wasmedge to 0.14.1

Update wasmedge version to 0.14.1

---

packaging/before-packaging-command/src/main.rs

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------
Process:               _moly_app [22638]
Path:                  /Applications/Moly.app/Contents/MacOS/_moly_app
Identifier:            _moly_app
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Exited process [22637]
User ID:               501
Date/Time:             2024-12-31 11:29:13.7184 +0800
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Bridge OS Version:     8.4 (21P4222)
Anonymous UUID:        38FD8E42-55B9-6552-B62A-10C3E31EE872
Sleep/Wake UUID:       A0EBF6FF-3DDF-4AB0-AF3A-BAF66E8CF9F7
Time Awake Since Boot: 990000 seconds
Time Since Wake:       11252 seconds
System Integrity Protection: …
```

Fix the incompatibility issue of libwasmedge.0.dylib on macos x86_64

---

Cargo.toml
moly-kit/src/widgets/chat.rs
moly-mini/src/demo_chat.rs

- Require Rust 1.81
- Chat tasks are executed/applied immediately instead of going through makepad's actions.
- This solves issues with tasks requiring to have always up to date state on the widgets and users hooking expecting the same.
- The hooking system now uses callbacks that can be set to modify tasks just before they are executed, or to just get notified after they occurred.
- You can still access the widget inside the hook with an `UiRunner` or communicating with raw makepad actions.

Tiny fixes + Chat hooks rework

---

moly-kit/src/utils.rs
moly-kit/src/utils/ui_runner.rs
moly-kit/src/widgets/chat.rs

- Clean up stream artifacts propertly.
- Abort streaming on unexpected modifications.
- Ensure we wait for the previous message delta to be processed before going to the next one. 
I recommend commenting the `self.messages_ref().write().scroll_to_bottom(cx);` line on `chat.rs` as the bug with auto scrolling will prevent you from trying  weird stuff like editing a previous message o deleting them while streaming.

Moly kit streaming fixes

---

moly-kit/src/clients/openai.rs

fixed EOF while parsing a value error in `moly-kit/src/clients/openai.rs`

fixed EOF while parsing a value error for MolyKit

---

moly-kit/src/clients/multi.rs
moly-kit/src/clients/openai.rs
moly-kit/src/protocol.rs
moly-kit/src/widgets/chat.rs
moly-kit/src/widgets/citations.rs
moly-kit/src/widgets/messages.rs
moly-mini/src/demo_chat.rs
moly-mini/src/lib.rs
moly-mini/src/tester_client.rs
moly-mini/src/ui.rs

- Define error kinds a client implementation should take into account.
- Flexible error representation, capable of carrying a recovery value alongside multiple errors.
- Adapted code on `moly-kit` and `moly-mini` to handle the basic errors.
- Low effort, `messages.rs` displays `App` massages as errors if they look like `xxx error: xxx`, by adapting `BotLine`, using the bot name to show the error name instead.
- Added a tester client to `moly-mini` to test error handling.
- Some on the go fixes and corrections.
- If you set wrong api keys, `moly-mini` should show you errors on start.
- Using the `tester` bot which should be default now on `moly-mini`, you can send `error` or `errors` to make the bot answer with one or many errors.

MolyKit error definitions and handling

---

README.md

Minor documentation convenience to link to the [moly-server repo](https://github.com/moxin-org/moly-server) in the README with brief usage explanation ([rendered](https://github.com/cass-uredium/moly/tree/document-server?tab=readme-ov-file#running-moly-with-moly-server)).

Document server usage in README

---

Cargo.lock
Cargo.toml
moly-kit/Cargo.toml
moly-kit/src/clients/deep_inquire.rs
moly-kit/src/clients/openai.rs
moly-kit/src/protocol.rs
moly-kit/src/widgets/messages.rs
moly-mini/src/tester_client.rs
moly-mini/src/ui.rs
src/data/chats/chat.rs

- Remove `hex` and `sha2` dependencies.
- `BotId`s are still created from a provider (discriminant) and an id from that provider.
- But now it's not hashed improving debugging as you see these components when printed.
- Now you can recover these sub components.
- `model_id` and `provider_id` in `Bot` are no longer necessary as they can be accessed like `bot.id.id()` and `bot.id.provider()` when necessary.
In order to allow any characters inside the components of the id, while allowing these components to be rescued, the id is encoded without separator characters. Instead the size of the first component is encoded into the id itself allowing you to directly extract the slice from the string without handling escaping or allocating new strings.
Having `bot.id.id()` may seem weird at first …

Unhashed but composed bot id 

---

src/chat/chat_screen.rs

Removing the usage of chat messages to report repo loading errors, this is causing some panics when deleting error messages (which should be fixed either way), but we're currently already handling and reporting this kind of errors in the providers dashboard.
In the future we could also report this with popup notifications.

Remove repo loading errors as chat messages

---

src/chat/chat_screen.rs
src/chat/model_selector.rs
src/chat/model_selector_item.rs
src/chat/model_selector_list.rs

Makes the model selector overlay the list of options on top of the chat, by using the Modal widget.

Make the model selector overlay the chat

---

moly-kit/src/widgets/chat.rs
moly-kit/src/widgets/messages.rs
src/chat/chat_screen.rs

- Updated scroll logic to trigger scrolling to the bottom only when not at the bottom of the message list.
- Introduced a deferred scroll mechanism in the Messages struct to handle scrolling after replacing the message list

Fix scroll to end behavior in chat

---

moly-kit/src/clients/deep_inquire.rs
moly-kit/src/clients/openai.rs
moly-kit/src/utils.rs
moly-kit/src/utils/errors.rs

- Added handling error reporting for unsuccesful responses
- Introduced a new `errors` module to handle HTTP error enrichment.
- Enhanced user feedback for common error scenarios such as rate limits and unauthorized access.
Example of a message to a Gemini model when exceeding daily or minute quota:

Add error enrichment for HTTP responses in MolyKit clients

---

.github/workflows/ci-build.yml
.github/workflows/release.yml
Cargo.toml
packaging/before-packaging-command/src/main.rs

Remove obsolete WasmEdge installation management from CI and packaging config--now migrated to moly-server (e.g. [`build.yml`](https://github.com/moxin-org/moly-server/blob/72a9e3edeb47bca5eb7770f117055347b08bbb26/.github/workflows/build.yml)).
Subsequent changes should be made to remove references to the old WasmEdge requirements from moly-runner and build.sh.

Remove WasmEdge installation management

---

moly-kit/src/widgets/prompt_input.rs
src/chat/chat_history.rs

Reusing portal list items ids for different templates (e.g. a ChatsHeader becomes an AgentsHeader when agents are loaded after chats).
This causes DrawList issues e.g.: `Drawlist id generation wrong index: 13 current gen:1 in pointer:0` and `Drawlist id generation wrong 13 1 0` this seems like a bug in PortalList. Disabling this feature until we have a solution

Temporarily disable agent buttons in chat history

---

moly-kit/src/widgets/message_loading.rs
moly-kit/src/widgets/prompt_input.rs
src/chat/chat_screen.rs
src/chat/model_selector_loading.rs

Disable the submit button of PromptInput while the repo is still loading. 
This prevents sending a message while the selected bot hasn't been loading into the repo yet.

Disable prompt while repo loading

---

moly-kit/src/widgets/message_markdown.rs
moly-kit/src/widgets/messages.rs

- Updated layout and styling for code blocks, including margins and background colors.
- Added a button to copy code from the code view to the clipboard, handling multiple code blocks within the Markdown widget.

Enhance MessageMarkdown code with styling and copy functionality

---

moly-kit/src/clients/deep_inquire/widgets/deep_inquire_content.rs
moly-kit/src/clients/deep_inquire/widgets/stages.rs
moly-kit/src/widgets.rs
moly-kit/src/widgets/avatar.rs
moly-kit/src/widgets/chat.rs
moly-kit/src/widgets/chat_lines.rs
moly-kit/src/widgets/citation.rs
moly-kit/src/widgets/citation_list.rs
moly-kit/src/widgets/message_loading.rs
moly-kit/src/widgets/message_markdown.rs
moly-kit/src/widgets/message_thinking_block.rs
moly-kit/src/widgets/messages.rs
moly-kit/src/widgets/prompt_input.rs
moly-kit/src/widgets/slot.rs
moly-kit/src/widgets/standard_message_content.rs
moly-kit/src/widgets/theme_moly_kit_light.rs

Latest Makepad includes some added spacing and padding to widgets that becomes very painful to override manually everywhere. 
Therefore we're introducing a MolyKit-specific theme that we can start using to override those values or create our own.
We're not overriding the linked Makepad theme as that has consequences for the entire application, not just the kit.
For more details check out the comments in the theme file.

Add MolyKit theming to fix some issues kit-wide

---

src/chat/chat_history_card.rs
src/chat/model_selector.rs

- Model selector now shows "No assistants available, check your provider settings" instead of "Choose your assistant" if there are no bots available.
- Unrelated, small UI fixes on chat history

Enhance ModelSelector by displaying assistant availability

---

moly-kit/src/clients/deep_inquire/widgets/deep_inquire_content.rs
moly-kit/src/clients/deep_inquire/widgets/stages.rs
moly-kit/src/widgets/avatar.rs
moly-kit/src/widgets/chat_lines.rs
moly-kit/src/widgets/citation.rs
moly-kit/src/widgets/message_markdown.rs
moly-kit/src/widgets/messages.rs
moly-kit/src/widgets/prompt_input.rs
moly-kit/src/widgets/standard_message_content.rs
src/app.rs
src/chat/chat_history.rs
src/chat/chat_history_card.rs

- Adds a smooth typing "animation" for standard messages, later on to include text fading.
- Enhances font sizing in general for the chat view (mostly upsizing)
DeepInquire does not benefit from this yet, we might want to make a wrapper around the markdown widget that can be re-used in DeepInquire to handle this animation, or just re-implement it independently in DeepInquire (as it might have some differences)
https://github.com/user-attachments/assets/515787c0-28ff-4516-b2a6-f45835f56d21
https://github.com/user-attachments/assets/22027a3a-6668-47d9-93cd-fd5947434267

Introduce smooth typing for streaming messages

---

moly-kit/src/widgets/chat.rs
src/chat/model_selector.rs
src/chat/model_selector_loading.rs
src/data/chats/mod.rs
src/data/openai_client.rs
src/data/store.rs
src/settings/add_provider_modal.rs
src/settings/provider_view.rs

- Fixes bugs with MolyServer, BotRepo and Providers hash map being out of sync
- Updates syncing status when updating single providers (not just in startup)
- Refactors provider registration to handle syncing/fetching models internally
- Show models as disabled in Provider view if the provider is disabled
- Makes the model loader loading line into a progress bar

Provider sync improvements

---

README.md

Provide more direct instructions for server usage and clean up surrounding language.
There is still room for improvement here, but this should suffice relative to its alpha state. In the future, something like an installer, Docker image, etc., would be more user-friendly.

Improve server usage documentation

---

moly-kit/src/clients/openai.rs
moly-kit/src/protocol.rs
moly-kit/src/widgets/message_thinking_block.rs
moly-kit/src/widgets/messages.rs
moly-kit/src/widgets/standard_message_content.rs

- Restores thinking blocks, recently they stopped working in Moly due to API changes on major providers. Instead of including the thinking content within <think> tags in the message content, providers now use a separate field, usually `reasoning` or `reasoning_content`.
- Improved the UI of thinking blocks and added an animation to show that thinking is happening.
https://github.com/user-attachments/assets/2111ea27-2ad5-4691-827c-abb085b3ff03

Improve thinking blocks

---

book/src/custom-client.md
book/src/custom-content.md
book/src/integrate.md
book/src/multiple-providers.md
book/src/quickstart.md
moly-kit/src/clients/deep_inquire.rs
moly-kit/src/clients/multi.rs
moly-kit/src/clients/openai.rs
moly-kit/src/protocol.rs
moly-kit/src/widgets/chat.rs
moly-kit/src/widgets/messages.rs
moly-mini/src/demo_chat.rs
moly-mini/src/tester_client.rs
src/chat/chat_screen.rs
src/data/store.rs

- Renamed `BotRepo` to `BotContext` to not confuse with repository pattern.
- Removed one-time `send` method from `BotClient`, and renamed `send_stream` to just `send`.

Some pending renaming and deleting from moly kit

---

src/app.rs

Previously we were dropping events in `app.rs` whenever the store wasn't loaded:
```rs
let Some(store) = self.store.as_mut() else {
self.ui.handle_event(cx, event, &mut Scope::empty());
return;
};
```
This was causing some makepad "setup" events like window geometry changes to be "dropped" by not being propagated to the main window (`self.ui.handle_event` wasn't called).
This PR fixes this issue by always calling `ui.handle_event`, and introducing a wrapper around the main Moly view, that only propagates events/draws downwards if the store is loaded. Almost the same as before but one level after the App struct.
Added a simple loading screen which we can animate later (almost impossible to see on native due to the store loading so quickly). …

Fix missing init events

---

Cargo.lock
moly-kit/Cargo.toml
moly-kit/src/clients/openai.rs
moly-kit/src/protocol.rs
moly-kit/src/utils.rs
moly-kit/src/widgets.rs
moly-kit/src/widgets/attachment_list.rs
moly-kit/src/widgets/chat.rs
moly-kit/src/widgets/prompt_input.rs
moly-kit/src/widgets/standard_message_content.rs

- Add protocol definitions for attachments.
- Update UI to be able to handle attachments.
- Update OpenAIClient to send loaded attachments.
- Only keep handle to attachment around instead of keeping its content in memory.
- `JsValue` handles on web are not `Send` so they can't cross `Cx::post_action` or `UiRunner` easily.
- Better icons, image previews, etc.
- Optional persistence, with low chance of file leaking. 
- Proper support outside of OpenAI.
- Currently seems to work well through direct OpenAI and OpenRouter, but fails for gemini and will need to be handled by clients that are not the OpenAIClient.

Web and native, multiple attachments, picking and sending support

---

moly-kit/src/clients/openai.rs

- Recognize `<think>` tag returned by distilled deepseek r1 models as reasoning content at `OpenAIClient`.
- Simplify reasoning handling there.

Restore think tag support

---

moly-kit/src/clients/deep_inquire.rs
moly-kit/src/clients/map.rs
moly-kit/src/clients/multi.rs
moly-kit/src/clients/openai.rs
moly-kit/src/clients/openai_image.rs
moly-kit/src/protocol.rs
moly-kit/src/utils/asynchronous.rs
moly-kit/src/widgets/chat.rs

- Removed the opaque wrapper types `MolyFuture` and `MolyStream` and their associated helper functions.
- Introduced the type aliases `BoxPlatformSendFuture` and `BoxPlatformSendStream` which are based on the `futures` crate boxed type aliases and can be constructed with a standard `Box::pin(...)` call.
- `amortize` function at `chat.rs` avoids an unnecessary dyn allocation.

Simplify boxed types at `asynchronous.rs`

---

moly-kit/src/widgets/chat.rs

The ChatView widget was experiencing panics with "Invalid slice range" errors when app error messages were inserted. The root cause was due to some missing task dispatching, specifically the intiial loading message from AI wasn't using an insert task, so if an error ocurred it would be inserted at message loading index + 1, but ChatView didn't have the loading message in its list until it was updated with the stream, making index + 1 out of range.
Adding a dispatch of the loading message caused a different error, a nested dispatch call breaking task execution order between the MolyKit Chat widget and ChatView synchronization:
**Expected vs Actual Task Order (when hooking from ChatView)**
- Expected: `insert(0, user_msg)` → `insert(1, loading_msg)` → `insert(2, error_msg) / or update`
- …

Fix nested dispatch causing out-of-order message synchronization

---

moly-kit/src/clients/openai.rs
moly-kit/src/clients/openai_realtime.rs
src/chat/chat_screen.rs
src/data/chats/mod.rs
src/data/mcp_servers.rs
src/data/preferences.rs
src/data/providers.rs
src/data/store.rs
src/mcp/mcp_servers.rs
src/settings/add_provider_modal.rs
src/settings/provider_view.rs

- Adds toggles to enable/disable MCP servers application wide, and also at the provider level.

Add app-wide and provider-wide MCP server controls
