moxin-org/moly

- Cargo.lock
- moxin-frontend/Cargo.toml
- moxin-frontend/moxin-fake-backend/src/fake_data.rs
- moxin-frontend/src/app.rs
- moxin-frontend/src/chat/chat_panel.rs
- moxin-frontend/src/chat/model_selector.rs
- moxin-frontend/src/data/download.rs
- moxin-frontend/src/data/mod.rs
- moxin-frontend/src/data/search.rs
- moxin-frontend/src/data/store.rs
- moxin-frontend/src/landing/landing_screen.rs
- moxin-frontend/src/landing/model_files_list.rs
Note there is no UI to track download progress yet
> File download. Initial intergration for front and backend.

- moxin-frontend/moxin-fake-backend/src/fake_data.rs
- moxin-frontend/src/data/chat.rs
- moxin-frontend/src/data/store.rs
Just some frontend modification references, no need to merge.
> Some suggestions.

- Cargo.lock
- moxin-frontend/Cargo.toml
- moxin-frontend/src/app.rs
- moxin-frontend/src/chat/chat_line.rs
- moxin-frontend/src/chat/chat_panel.rs
- moxin-frontend/src/chat/mod.rs
- moxin-frontend/src/data/chat.rs
- moxin-frontend/src/data/store.rs
Among other things, we are adding the ability to delete and edit messages.
> Add more features to chat

- moxin-frontend/src/chat/chat_panel.rs
Based on https://github.com/project-robius/moxin/pull/13#discussion_r1552732356
> Improve ChatPanel code using a state field

- moxin-frontend/src/data/download.rs
- moxin-frontend/src/data/store.rs
- Updates the Store with latest downloaded files, so that Chat and My Model screen update immediately
- Removes completed downloads from current downloads
> Fetch downloaded files after completion

- README.md
Add some dependency instructions required for compiling and running on the Linux platform to the README.
> update README for linux

- moxin-frontend/src/my_models/my_models_screen.rs
- moxin-frontend/src/shared/utils.rs
Implements the open folder mechanism for navigating the model downloads.
> Implement review in finder

- moxin-frontend/src/chat/chat_line.rs
- moxin-frontend/src/my_models/model_info_modal.rs
Preview:
https://github.com/project-robius/moxin/assets/22042418/121e86a8-7c5b-4ad5-94f2-5b783106fd43
Note: this PR requires https://github.com/makepad/makepad/pull/455 to be merged.
> Implement copy buttons in chat and model Info

- moxin-frontend/src/my_models/downloaded_files_table.rs
- moxin-frontend/src/my_models/my_models_screen.rs
Implements search in My Models:
- Applies filtering each time text input changes
- If there's a current search, and a new download is completed that matches the search, the results are immediately updated
- I've kept the default sorting by download date desc.
> Implement Search in My Models

- moxin-frontend/src/chat/chat_line.rs
- moxin-frontend/src/chat/chat_panel.rs
- moxin-frontend/src/landing/search_bar.rs
- moxin-frontend/src/my_models/my_models_screen.rs
- moxin-frontend/src/shared/widgets.rs
Restores the styling of text inputs to the previous shaders.
> Fix text input styling

- moxin-frontend/src/landing/model_card.rs
- moxin-protocol/src/protocol.rs
> Fix external links alignment

- moxin-frontend/src/app.rs
- moxin-frontend/src/data/search.rs
- moxin-frontend/src/data/store.rs
- moxin-frontend/src/landing/landing_screen.rs
- moxin-frontend/src/landing/mod.rs
- moxin-frontend/src/landing/model_files_list.rs
- moxin-frontend/src/landing/model_list.rs
- moxin-frontend/src/landing/search_bar.rs
- moxin-frontend/src/landing/search_loading.rs
Changes:
* Search action is now debounced, so it feels more natural.
* Added loading animation (see video).
* Make sure expanded files are reset when sorting or changing the search keyword.
* Some additions to fake data (only visible when running with `FILL_FAKE_DATA=true`)
https://github.com/project-robius/moxin/assets/487140/cfca8e4f-4183-42c7-b57d-021bfdf09200
> Improvements for searching models

- moxin-frontend/src/app.rs
- moxin-frontend/src/data/chat.rs
- moxin-frontend/src/data/download.rs
- moxin-frontend/src/landing/model_files_list.rs
- moxin-frontend/src/landing/model_list.rs
- moxin-frontend/src/landing/search_loading.rs
- Improve how the model files list is being rendered, to make sure Download buttons is always responsive.
- Fix issue with loading animation that was causing a large number of Draw events.
- Prevent an issue where an infinite loop related with file downloads were flooding the UI with signal events.
> Fixing download issues

- moxin-frontend/src/landing/model_card.rs
> Update model like and download counts style.

- moxin-frontend/src/app.rs
- moxin-frontend/src/chat/chat_line.rs
- moxin-frontend/src/chat/chat_line_loading.rs
- moxin-frontend/src/chat/chat_panel.rs
- moxin-frontend/src/chat/mod.rs
- moxin-frontend/src/landing/model_list.rs
Adds the loading animation when the chat model response is about to streaming:
(animation is working similar to Figma).
> Chat: show loading animation when waiting for first token

- moxin-frontend/src/app.rs
- moxin-frontend/src/shared/styles.rs
- moxin-frontend/src/shared/widgets.rs
> Sidebar design updates

- moxin-backend/src/store/download_files.rs
Fixes an issue where files weren't being shown as downloaded in the model cards. (unless you performed a search that returned a single model card)
This was happening because querying download files by multiple model IDs using the `get_by_models` function returned an empty result. 
Due to that empty result, the file mapping in `RemoteModel::to_model` would not include data from the local files, i.e. downloaded path, if it was downloaded or not, etc.
Therefore, the files listed in the UI only had the remote file data, and no local file data if a search pattern matched with more than 1 model.
The problem with querying was caused by incorrect usage of the `IN` clause in the SQL query when passing multiple IDs:
In SQLite, when you use IN with a single parameter (`WHERE model_id IN (?1)`), it …
> Fix querying download files by multiple model IDs

- moxin-frontend/src/landing/search_loading.rs
Adds linear gradient color to the loading dots in the search loading animation
> Add color gradient to search loading animation

- moxin-frontend/src/chat/chat_panel.rs
- moxin-frontend/src/data/chat.rs
- moxin-frontend/src/data/store.rs
- moxin-frontend/src/landing/model_files_list.rs
- moxin-frontend/src/landing/search_bar.rs
- moxin-frontend/src/my_models/delete_model_modal.rs
- moxin-frontend/src/my_models/model_info_modal.rs
- moxin-frontend/src/my_models/my_models_screen.rs
Adds some minor front end fixes that we committed to a separate branch for demo purposes. Mostly warning fixes and UI adjustments.
> Demo Fixes

- moxin-frontend/src/chat/chat_history.rs
Adds model photo to chat history card and updates some styles
> add model photo to chat history card

- README.md
Merge this after merging in PR #104, as this refers to some changes made in that PR.
> Update README with packaging details and links

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- moxin-runner/Cargo.toml
- moxin-runner/src/main.rs
- src/main.rs
Signing and notarization also works now. Ready for release!
> Fix macos app bundles by directly packaging wasmged dylibs into bundle

- src/chat/chat_history_card.rs
- src/chat/chat_panel.rs
- src/data/chats/chat.rs
- src/data/chats/mod.rs
- src/data/store.rs
Some refactors and simplifications after last minute fixes. It depends on improvements done in #98.
> Improve multiple chats logic

- src/data/search/faked_models.rs
- src/landing/model_files.rs
- src/shared/widgets.rs
https://github.com/moxin-org/moxin/assets/487140/3642911f-601a-42a0-9926-3066bedf6ddd
> Redesign for show all/only recommended files

- src/chat/chat_panel.rs
- src/chat/chat_screen.rs
https://github.com/moxin-org/moxin/assets/487140/8ddd3815-5252-4dc8-90ce-1cb9b8a0fc2c
> Do not change chat section width on sidebar collapse/expand

- Cargo.toml
- README.md
- packaging/moxin.desktop
Includes selected changes from 4 of my PRs to cargo-packager
> Update to our latest forked version of `cargo-packager`

- moxin-protocol/src/open_ai.rs
> chore: update open_ai.rs

- src/chat/chat_panel.rs
https://github.com/orgs/moxin-org/projects/1/views/1?pane=issue&itemId=71621461
> Allow chat panel to take all available width

- src/chat/chat_line.rs
- src/chat/chat_panel.rs
https://github.com/orgs/moxin-org/projects/1/views/1?pane=issue&itemId=71621481
> Styling adjustments for chat bubbles UI

- moxin-runner/src/main.rs
Depends on #198.
~~Things... sort of work? There seems to be a strange bug where the application hangs until the user presses a key in the terminal. But that only happens when the CUDA version of the WASI-nn plugin is active.~~
this is an unrelated bug.
> Windows cuda support

- Cargo.lock
- src/chat/chat_panel.rs
> After clicking on "Chat with Model", set keyboard focus to the Chat panel's prompt

- src/landing/search_bar.rs
Fixes #237 
I want to implement a feature where the X button appears when the mouse clicks on the input field or when the user types something, and it stays hidden at other times. But I haven't found a good way to achieve this yet.
> Add Clear Text Button to Models Search Bar

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/chat/chat_line.rs
> Add syntax highlighting to markdown code blocks

- src/app.rs
- src/chat/model_selector.rs
- src/landing/model_files_item.rs
- src/my_models/downloaded_files_row.rs
> refactor ChatAction

- src/app.rs
- src/chat/chat_panel.rs
- src/my_models/delete_model_modal.rs
> refactor ChatPanelAction

- src/app.rs
- src/landing/download_item.rs
- src/landing/model_files_item.rs
- src/shared/download_notification_popup.rs
These two actions are really closely related. Originally, I wanted to refactor them separately, but it would cause conflicts, and I wouldn't be able to test the functionality. so I decided to refactor them both at the same time.
> refactor ModelFileItemAction and DownloadAction

- moly-backend/src/backend_impls/api_server.rs
Issue: https://github.com/moxin-org/moly/issues/206
Take cancellation into account when:
- We still didn't receive the first part of the HTTP response.
- We still didn't drain and parse the full body stream when one-shot JSON response is expected. 
https://github.com/user-attachments/assets/8fec218c-ede2-468b-ac88-4c1f900cc3fc
https://github.com/user-attachments/assets/d7d1bc7e-f501-4b74-a481-575158105c01
> Allow stop button to work before any kind of response comes from the server

- .mega/config.toml
- Cargo.lock
- moly-backend/Cargo.toml
- moly-backend/src/lib.rs
- moly-backend/src/store/model_cards.rs
- moly-backend/src/store/remote.rs
- src/main.rs
- p2p download
- support add & share model to p2p network
// todo: support both `p2p` & `http` protocols
> Support P2P download & upload models via `Mega`

- moly-mofa/src/lib.rs
- src/data/store.rs
Changes
- Fix mofa client fake impl
- Always insert default mofa server
- Also, some auto-formatting
> Some mofa fixes

- Cargo.lock
- Cargo.toml
- moly-mofa/src/lib.rs
- src/chat/chat_panel.rs
- src/chat/entity_button.rs
- src/chat/prompt_input.rs
- src/data/chats/chat_entity.rs
- src/data/store.rs
> Depends on Makepad PR: https://github.com/makepad/makepad/pull/621. Update makepad dependency if that gets merged.
Extracted most logic related to the popup text input of `PromptInput` to a makepad widget and modified `PromptInput` with it.
Didn't extract some Moly specific details like items filtering logic, template format, specific style overrides, etc.
> Extract prompt input popup logic to makepad

- moly-mofa/src/lib.rs
See the description of https://github.com/moxin-org/moly/pull/336
> Bypass proxy in MoFa server clients

- README.md
- moly-mofa/src/lib.rs
- src/chat/chat_history.rs
- src/chat/model_selector_list.rs
- src/chat/prompt_input.rs
- src/landing/model_list.rs
- src/settings/settings_screen.rs
Changes:
* Remove visibility checks
* Update README with detailed setup instructions
* `MOFA_BACKEND` is now `real` by default.
> Make MoFa integration a permanent feature

- src/data/moly_client.rs
Solve the conflict between VPN and localhost. 
```
Running `target/debug/_moly_app`
Error fetching downloaded files: Server error: 502 Bad Gateway
iError fetching pending downloads: Server error: 502 Bad Gateway
^R
Error fetching models: Server error: 502 Bad Gateway
Error fetching models from the server
```
> Correct the request to access localhost to use no_proxy

- moly-kit/src/clients/multi.rs
- moly-kit/src/clients/openai.rs
- moly-kit/src/protocol.rs
- moly-kit/src/widgets.rs
- moly-kit/src/widgets/chat.rs
- moly-kit/src/widgets/citations.rs
- moly-kit/src/widgets/messages.rs
Same as PR https://github.com/moxin-org/moly/pull/382 but merging into `dev` because for some reason the base branch didn't change automatically and some conflicts appeared.
> Molykit tiny cleanup

- moly-kit/src/clients/openai.rs
- On native platforms, added timeouts for API calls.
- Simplified a little bit the code and reduced risk of deadlocks.
> OpenAIClient connection handling improvements 

- README.md
- src/data/chats/mod.rs
- src/data/openai_client.rs
- src/data/supported_providers.json
- src/data/supported_providers.rs
Unifies the definition of supported providers and their whitelisted models.
> Move supported models definition into supported_providers.json

- moly-kit/src/clients/deep_inquire.rs
Resolves intermittent timeout issues with DeepInquire API by reducing back-pressure in the SSE stream processing. Updates UI every 10 messages instead of for every message, preventing network buffer overflows and subsequent timeouts during high-frequency word-by-word streaming.
Ideally this should be fixed on the server side by doing more efficient streaming.
> Fix: Prevent DeepInquire SSE stream timeouts

- src/data/moly_client.rs
- src/data/store.rs
- src/settings/moly_server_screen.rs
Take into consideration the connected flag inside moly's MolyClient.
> consider moly server enabled flag

- moly-kit/src/clients/openai.rs
- moly-kit/src/widgets/avatar.rs
- moly-kit/src/widgets/messages.rs
- src/chat/chat_history_card.rs
- src/chat/chat_screen.rs
- src/chat/model_selector.rs
- src/chat/model_selector_loading.rs
- src/chat/shared.rs
- src/data/chats/mod.rs
- src/data/store.rs
- Fixed an issue with portal list range when switching to a new chat
- Restored the ModelSelector loading animation, now used to show if the list of bots is still being updated/synced
- Avatar characters are now always uppercase (lowercase characters like `y` and `p` didn't look centered)
> Minor UI improvements

- moly-kit/src/clients/deep_inquire/widgets/stages.rs
- moly-kit/src/widgets/citation.rs
- src/chat/chat_history.rs
- src/chat/prompt_input.rs
- src/settings/providers.rs
- Moves sources section on top of the stage content instead of at the end, so that streaming doesn't push it down constantly
- Added an animation to the stage bubble when it's streaming
- Some general minor UI improvements
> DeepInquire UI improvements

- moly-kit/src/widgets/chat.rs
- moly-kit/src/widgets/messages.rs
- Fixed stick to bottom preventing manual user scrolling
- Fixed jump to bottom button flickering
- Jump to bottom now re-triggers stick to bottom if clicked during stream, after previously interrupting it
Some of this behavior is slightly spread between `Chat` and `Messages` which I don't love but I wanted each widget to keep track of their own needs. Also the tasks mechanism, and some limitations of actions/events of PortalList force me to be a bit redundant to ensure consistency and prevent some race conditions.
> Enhance chat stick to bottom behaviour

- src/chat/chat_screen.rs
- Add the missing `SetMessages` task handling.
- Auto formatting
> Fix save & regenerate

- moly-kit/src/clients/deep_inquire/widgets/deep_inquire_bot_line.rs
- moly-kit/src/widgets.rs
- moly-kit/src/widgets/chat_lines.rs
- moly-kit/src/widgets/message_content_view.rs
- moly-kit/src/widgets/messages.rs
- moly-kit/src/widgets/standard_message_content.rs
- Take out message content from messages.rs.
- Simplify related DSLs, like chat lines DSL.
> Move message content out

- src/data/chats/mod.rs
- src/data/deep_inquire_client.rs
- src/data/downloads/download.rs
- src/data/downloads/mod.rs
- src/data/moly_client.rs
- src/data/openai_client.rs
- src/data/providers.rs
- src/data/search/mod.rs
- src/data/store.rs
Removes many unnecessary channels and removes a lot of code
> Clean after web

- moly-kit/src/clients/deep_inquire.rs
- src/chat/chat_screen.rs
- src/chat/model_info.rs
- src/chat/model_selector.rs
- src/chat/model_selector_item.rs
- src/chat/model_selector_list.rs
- src/data/store.rs
- Adds provider icons to the select model and to the section labels in the model selector
> Use provider icons in model selector

- Cargo.lock
- Cargo.toml
- moly-kit/Cargo.toml
- moly-mini/Cargo.toml
- src/app.rs
- src/chat/chat_screen.rs
- src/chat/chat_view.rs
- src/settings/provider_view.rs
- src/settings/providers.rs
- src/settings/providers_screen.rs
- Introduces the main AdaptiveView widget instances that will be used for making Moly responsive.
- Switch to rustls-tls backend to resolve OpenSSL linking errors on Android devices.
> Groundwork for responsive layout

- Cargo.lock
- README.md
- moly-kit/src/utils/asynchronous.rs
- src/app.rs
- src/chat/chat_screen_mobile.rs
- src/chat/chat_view.rs
- src/data/chats/mod.rs
- src/data/preferences.rs
- src/lib.rs
- src/main.rs
- src/runtime.rs
- src/shared/utils/filesystem/adapter.rs
- src/shared/utils/filesystem/adapters/android.rs
- src/shared/utils/filesystem/adapters/mobile.rs
- src/shared/utils/filesystem/adapters/mod.rs
- src/shared/utils/filesystem/mod.rs
Adds support for mobile platforms by reworking some limitations with async and filesystem usage.
- Make async utilities runtime-aware, if not running inside a runtime (e.g. Android) create one on demand.
- Add filesystem adapters for mobile
> Filesystem and Async support for Mobile Platforms

- moly-kit/src/widgets/messages.rs
- src/app.rs
- src/chat/chat_screen_mobile.rs
- src/chat/chat_view.rs
- src/chat/chats_deck.rs
- src/chat/model_selector.rs
- src/settings/provider_view.rs
- src/settings/providers.rs
- src/settings/providers_screen.rs
General minor UI improvements for responsiveness
> Responsivness improvements

- Cargo.lock
- moly-kit/Cargo.toml
- moly-kit/src/clients.rs
- moly-kit/src/clients/openai.rs
- moly-kit/src/clients/openai_image.rs
- moly-kit/src/protocol.rs
- moly-kit/src/utils.rs
- moly-kit/src/utils/platform.rs
- moly-kit/src/widgets/attachment_list.rs
- moly-kit/src/widgets/prompt_input.rs
- moly-kit/src/widgets/standard_message_content.rs
- moly-mini/src/demo_chat.rs
- moly-mini/src/ui.rs
- src/chat/chat_screen.rs
- src/data/mod.rs
- src/data/openai_image_client.rs
- src/data/providers.rs
- src/data/supported_providers.json
- src/settings/add_provider_modal.rs
- Adds support for OpenAI image generation models to Moly Kit.
- Implements the `BotClient` trait.
- Uses attachments feature backbone, so improvements to the attachments feature (like previews and persistence) will improve this feature as well.
- Can be tested through moly-mini.
- Adds OpenAI image generation provider settings main moly app.
- Done, BUT **see PR comments for details**.
> Image generation

- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- moly-kit/Cargo.toml
- moly-kit/src/widgets/realtime.rs
- moly-mini/Cargo.toml
- packaging/Info.plist
- packaging/before-packaging-command/Cargo.toml
Bumps makepad to introduce proper microphone permission management. 
https://github.com/user-attachments/assets/58394d76-9c96-47dc-8560-db38ab2fd6f7
> Handle microphone permission for realtime audio
